# Generated by Django 4.1.13 on 2023-12-18 21:49

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
    ]
